## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Saint-Augustin,CA,51.2260,-58.6502,25.81,94,100,16.51,overcast clouds
1,1,Bredasdorp,ZA,-34.5322,20.0403,66.20,72,0,13.80,clear sky
2,2,Cap-Aux-Meules,CA,47.3821,-61.8597,19.40,86,100,17.27,overcast clouds
3,3,Tuktoyaktuk,CA,69.4541,-133.0374,-4.00,84,90,5.75,light snow
4,4,Invermere,CA,50.5167,-116.0354,35.01,92,100,1.01,overcast clouds

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
8,8,Urucara,BR,-2.5364,-57.7600,83.80,78,99,0.94,overcast clouds
9,9,Mahebourg,MU,-20.4081,57.7000,80.60,78,75,4.61,broken clouds
11,11,Vaini,TO,-21.2000,-175.2000,78.80,94,75,9.22,broken clouds
12,12,Cidreira,BR,-30.1811,-50.2056,76.15,58,7,11.56,clear sky
17,17,Rikitea,PF,-23.1203,-134.9692,79.93,82,16,12.08,few clouds
20,20,Chunhuhub,MX,19.5500,-88.6833,89.94,42,61,3.69,broken clouds
22,22,Cayenne,GF,4.9333,-52.3333,75.20,94,75,8.05,moderate rain
32,32,Butaritari,KI,3.0707,172.7902,79.84,81,38,14.58,scattered clouds
35,35,Manadhoo,MV,5.7667,73.3833,83.01,64,0,6.85,clear sky
38,38,Saint-Joseph,RE,-21.3667,55.6167,78.80,78,90,4.61,overcast clouds

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                200
City                   200
Country                200
Lat                    200
Lng                    200
Max Temp               200
Humidity               200
Cloudiness             200
Wind Speed             200
Current Description    200
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.count().dropna
clean_df.head(10)

AttributeError: 'function' object has no attribute 'head'

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

NameError: name 'clean_df' is not defined

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

In [9]:
# 7. Drop the rows where there is no Hotel Name.

In [10]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure